services:
  - type: web
    name: finance-app-api
    runtime: python
    startCommand: cd backend && pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000
    plan: free
    region: ohio
    autoDeploy: true

databases:
  - name: finance-mongo
    databaseName: finance
    ipAllowList: []
